                # uses BCM GPIO pin numbers
    rs     = 17 # GPIO 0  Physical pin 11 RS ie reset  goes to display pin 4
    enable = 27 # GPIO 2  physical pin 13 E ie Strobe  goes to display pin 6 (also known as Enable)
    data4  = 22 # GPIO 3  physical pin 15	           goes to display pin 11
    data5  = 23 # GPIO 4  physical pin 16 	           goes to display pin 12
    data6  = 24 # GPIO 5  physical pin 18	           goes to display pin 13
    data7  = 25 # GPIO 6  physical pin 22	           goes to display pin 14
                #         physical pin 25 & 6 gnd      goes to display 1
                #                          brightness  goes to display 3
                #         physical pin 2     +5        goes to display 2
                #                            gnd       goes to display 16 (lighing gnd))
                #         physical pin 4   dispay +5   goes to dispaly 15 (Anode lighting diode power)